#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
  colorscheme = "dracula"
  colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
  enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  filetree_direction="left"
  filemanager = "vimfiler"
  default_indent = 2
  project_rooter_patterns = ['go.mod', 'Gopkg.toml' ,'.git/']
  bootstrap_before = 'init#before'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#go"

[[layers]]
  name = "format"

[[layers]]
name = "fzf"

[[layers]]
  name="git"

[[layers]]
  name = "lang#markdown"
  enabled_formater=['prettier']
  
[[layers]]
  name = "lang#sh"

[[custom_plugins]]
  repo = "dracula/vim"
  merge = false

[[custom_plugins]]
  repo = "terryma/vim-multiple-cursors"
  merge = false

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "tools"

[[layers]]
  name = "lang#python"

[[layers]]
  name="lsp"
  filetypes=[
    "go"
  ]
